name: Minimal Testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Dependency (ubuntu)
        run: |
          # for GUI widget testing
          sudo apt-get install xvfb -y

      - name: Dependency (pip)
        run: |
          # testing tools & visualization packages
          python -m pip install invoke pytest pandas matplotlib bokeh
          pip install -r requirements.txt
      - name: Customized calmap
        run: |
          # it matters to use this repo to adapt the customized bug fix
          git clone https://github.com/zztin/calmap
          cd calmap
          python setup.py install
      - name: Packaging
        run: |
          python ${GITHUB_WORKSPACE}/setup.py install
          which ctimer

      - name: PyTest Cases
        run: |
          # used for tkinter widget test cases
          # otherwise tkinter will complain when running on github action
          # "_tkinter.TclError: no display name and no $DISPLAY environment variable"
          Xvfb :99 &
          export DISPLAY=:99

          inv test
